name: Hello World Check

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install uv package manager
        run: |
          python3 -m pip install --user uv
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - name: Install HermesBaby
        run: |
          uv tool install hermesbaby
          uv tool update-shell
          hermesbaby --version
      - name: Install HermesBaby's toolbox
        run: |
          source .github/workflows/mock_hb_tools_install.sh
      - name: Build site
        run: |
          hb html
